package com.example.auro.lib.constants;

public enum Direction {

	FORWARD, BACKWARD, LEFT, RIGHT, DIAGONAL_FORWARD_LEFT, DIAGONAL_FORWARD_RIGHT, DIAGONAL_BACKWARD_LEFT, DIAGONAL_BACKWARD_RIGHT, FORWARD_LEFT,
	FORWARD_RIGHT, BACKWARD_LEFT, BACKWARD_RIGHT
}
